### ISSUE TITLE
clean up css / js assets pulled in

### ISSUE THREAD

**Issue by btopro** [LRNWebComponents/pdf-element#2]
most likely fixing this will fix the other issue but you shouldn't do things like 
```
<link rel="stylesheet" href="../pdfjs-dist/web/pdf_viewer.css">
```
in elements.

Instead, the contents of those files should be placed in their own element and then referenced; either that or a single element which implements / references these things and then to integrate w/ it people would just reference the element (which would just import css / js stuff; weird I know but legit).

Note how colors get pulled in in the materializecss-styles component -- https://github.com/LRNWebComponents/materializecss-styles

**Comment by proconnor15** [comment]
Fixed the css and js pulled in by creating files two files that contained the code and put that in the file directory.

**Comment by btopro** [comment]
https://github.com/LRNWebComponents/pdf-element now in!
